name: Python application

on:
  push:
    branches: ["main", "master", "staging"]
  pull_request:
    branches: ["main", "master", "staging"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pytest maturin
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt --no-build-isolation; fi

      - name: Build and install Rust extension
        run: maturin develop

      - name: Test with pytest
        run: pytest
